apiVersion: apps/v1
kind: Deployment
metadata:
  name: moq-api
spec:
  selector:
    matchLabels:
      app: moq-api
  replicas: 1
  template:
    metadata:
      labels:
        app: moq-api
    spec:
      volumes:
        - name: keys-volume
          secret:
            secretName: keys
      containers:
        - name: moq-api
          image: vidarhun/moq-rs
          volumeMounts:
            - name: keys-volume
              mountPath: /certs
          command: ["moq-api", "--listen", "0.0.0.0:4442", "--redis", "redis://redis.default.svc.cluster.local:6379"]
          ports:
            - containerPort: 4442
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: moq-api-svc
spec:
  selector:
    app: moq-api
  ports:
    - protocol: TCP
      port: 4442
      targetPort: 4442
  clusterIP: None
