apiVersion: v1
kind: ConfigMap
metadata:
  name: app-server
data:
  config.yaml: |
    quicrq:
      address: "127.0.0.1"
      port: 3000

    database:
      address: "127.0.0.1"
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: net-debug
        image: l7mp/net-debug
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: app-server
        image: vidarhun/app_server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-server
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
